name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: "Marlon-Mena"  # Substitua pelo seu nome de usuário
          svg_out_path: dist/snake.svg  # Caminho de saída da imagem SVG

      - name: Commit and push the Snake animation
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Branch onde a imagem será publicada
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
